"use client";
/* eslint-disable react-hooks/static-components, react/no-unescaped-entities */

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { Activity, Bot, BookOpen, Box, Check, ChevronRight, CircleGauge, Database, Gauge, GitCompareArrows, Home, Info, Menu, PackageSearch, RotateCcw, Save, Search, Settings2, ShieldCheck, Sparkles, Stethoscope, UserRound, Users, Wrench, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";

type View = "accueil" | "assistant" | "configurateur" | "diagnostic" | "base" | "pieces" | "eclate" | "garage" | "pro";
type PartKey = "cylinder" | "carb" | "exhaust" | "ignition" | "transmission";

const vehicles = [
  ["Aprilia", "RS 50", "route 50", "Minarelli AM6", "1993–2014"], ["Aprilia", "RX 50", "enduro 50", "Minarelli AM6", "1995–2020"], ["Aprilia", "SX 50", "supermotard 50", "Derbi D50B0", "2006–2020"],
  ["Beta", "RR 50", "enduro 50", "Minarelli AM6", "2005–2026"], ["Beta", "RR 50 Motard", "supermotard 50", "Minarelli AM6", "2005–2026"], ["Rieju", "MRT 50", "enduro 50", "Minarelli AM6", "2009–2026"],
  ["Rieju", "MRT SM 50", "supermotard 50", "Minarelli AM6", "2009–2026"], ["Sherco", "SE 50", "enduro 50", "Minarelli AM6", "2014–2026"], ["Sherco", "SM 50", "supermotard 50", "Minarelli AM6", "2014–2026"],
  ["Yamaha", "DT 50", "enduro 50", "Minarelli AM6", "1997–2011"], ["Yamaha", "TZR 50", "route 50", "Minarelli AM6", "1996–2016"], ["MBK", "X-Limit", "enduro 50", "Minarelli AM6", "1997–2012"],
  ["Peugeot", "XP6", "enduro 50", "Minarelli AM6", "1997–2012"], ["Malaguti", "XSM 50", "supermotard 50", "Minarelli AM6", "2003–2011"], ["Motorhispania", "Ryz 50", "supermotard 50", "Minarelli AM6", "2004–2014"],
  ["Fantic", "Caballero 50", "enduro 50", "Minarelli AM6", "2006–2020"], ["Derbi", "Senda 50", "enduro 50", "Derbi EBS/D50B0", "1994–2020"], ["Gilera", "SMT 50", "supermotard 50", "Derbi D50B0", "2003–2020"],
  ["Aprilia", "SR 50", "scooter", "Piaggio/Minarelli", "1992–2020"], ["Yamaha", "Aerox", "scooter", "Minarelli horizontal", "1997–2021"], ["MBK", "Nitro", "scooter", "Minarelli horizontal", "1997–2012"],
  ["Piaggio", "Zip 50 2T", "scooter", "Piaggio Hi-Per2", "1992–2017"], ["Peugeot", "Speedfight 2", "scooter", "Peugeot horizontal", "2000–2009"], ["Gilera", "Runner 50", "scooter", "Piaggio Hi-Per2", "1997–2020"],
  ["KTM", "65 SX", "motocross 65", "KTM 65", "1998–2026"], ["KTM", "85 SX", "motocross 85", "KTM 85", "2003–2026"], ["Husqvarna", "TC 85", "motocross 85", "KTM 85 family", "2014–2026"],
  ["GasGas", "MC 85", "motocross 85", "KTM 85 family", "2021–2026"], ["Yamaha", "YZ85", "motocross 85", "Yamaha 85", "2002–2026"], ["Kawasaki", "KX85", "motocross 85", "Kawasaki 85", "2001–2026"],
  ["Honda", "CR125R", "motocross 125", "Honda CR125", "1982–2007"], ["Yamaha", "YZ125", "motocross 125", "Yamaha YZ125", "1974–2026"], ["KTM", "125 SX", "motocross 125", "KTM 125", "1998–2026"],
  ["KTM", "125 EXC", "enduro 125", "KTM 125", "1998–2016"], ["Husqvarna", "TE 125", "enduro 125", "KTM 125 family", "2014–2016"], ["GasGas", "EC 125", "enduro 125", "GasGas 125", "1997–2015"],
  ["Aprilia", "RS 125", "route 125", "Rotax 122/123", "1992–2012"], ["Cagiva", "Mito 125", "route 125", "Cagiva 125", "1990–2012"], ["Honda", "NSR125R", "route 125", "Honda JC20/22", "1988–2003"],
  ["Yamaha", "TZR125", "route 125", "Yamaha 2RH/4DL", "1987–1999"], ["Suzuki", "RG125 Gamma", "route 125", "Suzuki 125", "1985–1991"], ["Kawasaki", "KDX125SR", "trail 125", "Kawasaki KDX125", "1990–1999"],
  ["Honda", "CR250R", "motocross 250", "Honda CR250", "1973–2007"], ["Yamaha", "YZ250", "motocross 250", "Yamaha YZ250", "1974–2026"], ["KTM", "250 SX", "motocross 250", "KTM 250", "1998–2026"],
  ["KTM", "250 EXC", "enduro 250", "KTM 250", "1998–2026"], ["Husqvarna", "TE 250", "enduro 250", "KTM 250 family", "2014–2026"], ["GasGas", "EC 250", "enduro 250", "GasGas/KTM 250", "1997–2026"],
  ["Beta", "RR 250 2T", "enduro 250", "Beta 250", "2013–2026"], ["Sherco", "250 SE", "enduro 250", "Sherco 250", "2014–2026"], ["KTM", "300 EXC", "enduro 300", "KTM 300", "1998–2026"],
  ["Husqvarna", "TE 300", "enduro 300", "KTM 300 family", "2014–2026"], ["GasGas", "EC 300", "enduro 300", "GasGas/KTM 300", "1999–2026"], ["Beta", "RR 300 2T", "enduro 300", "Beta 300", "2013–2026"],
  ["Sherco", "300 SE", "enduro 300", "Sherco 300", "2014–2026"], ["TM", "EN 300", "enduro 300", "TM 300", "2000–2026"], ["Yamaha", "RD350 LC", "route historique", "Yamaha 347 twin", "1980–1995"],
  ["Suzuki", "RG500 Gamma", "route historique", "Suzuki square-four", "1985–1987"], ["Honda", "NSR250R", "route historique", "Honda V-twin", "1987–1996"], ["Kawasaki", "H2 750", "route historique", "Kawasaki triple", "1972–1975"],
  ["KTM", "380 EXC", "enduro historique", "KTM 380", "1998–2002"], ["Honda", "CR500R", "motocross 500", "Honda CR500", "1984–2001"], ["Kawasaki", "KX500", "motocross 500", "Kawasaki KX500", "1983–2004"],
] as const;

const partOptions: Record<PartKey, {name:string; price:number; status:"Compatible"|"Sous conditions"; delta:number; note:string}[]> = {
  cylinder: [{name:"Cylindre d'origine 49,7 cm³",price:0,status:"Compatible",delta:0,note:"Configuration de référence"},{name:"Kit sport 70 cm³ aluminium",price:249,status:"Sous conditions",delta:3,note:"Carburation et échappement à adapter"},{name:"Kit couple 80 cm³",price:329,status:"Sous conditions",delta:5,note:"Vilebrequin renforcé recommandé"}],
  carb: [{name:"Carburateur 16 mm d'origine",price:0,status:"Compatible",delta:0,note:"Réglage constructeur"},{name:"Carburateur type PWK 21",price:119,status:"Compatible",delta:1,note:"Gicleur à calibrer"},{name:"Carburateur type PWK 24",price:149,status:"Sous conditions",delta:2,note:"Admission compatible nécessaire"}],
  exhaust: [{name:"Échappement d'origine",price:0,status:"Compatible",delta:0,note:"Homologation selon véhicule"},{name:"Détente sport 50/70",price:229,status:"Compatible",delta:2,note:"Accord moyen/haut régime"},{name:"Détente racing 70/80",price:299,status:"Sous conditions",delta:4,note:"Usage route à vérifier"}],
  ignition: [{name:"Allumage d'origine",price:0,status:"Compatible",delta:0,note:"Fiabilité maximale"},{name:"Rotor interne digital",price:349,status:"Sous conditions",delta:2,note:"Éclairage et calage à contrôler"}],
  transmission: [{name:"Transmission 13 × 53",price:0,status:"Compatible",delta:0,note:"Référence de démonstration"},{name:"Transmission 14 × 52",price:42,status:"Compatible",delta:1,note:"Allonge accrue, reprise réduite"},{name:"Transmission 12 × 54",price:42,status:"Compatible",delta:-1,note:"Reprise accrue, allonge réduite"}],
};

const catalogParts = [
  ["OEM-AM6-PISTON-STD","Piston standard AM6","Haut moteur","Minarelli AM6","Compatible directement","OEM / à vérifier"],
  ["OEM-AM6-GASKET-TOP","Pochette joints haut moteur","Haut moteur","Minarelli AM6","Compatible sous conditions","Référence technique"],
  ["AF-70-ALU-AM6","Kit cylindre aluminium 70 cm³","Cylindre","Minarelli AM6","Adaptation nécessaire","Aftermarket"],
  ["AF-PWK-21","Carburateur type PWK 21 mm","Carburation","Multi-moteurs","Compatible sous conditions","Aftermarket"],
  ["AF-PWK-24","Carburateur type PWK 24 mm","Carburation","Multi-moteurs","Compatible sous conditions","Aftermarket"],
  ["AF-REEDS-AM6","Boîte à clapets renforcée","Admission","Minarelli AM6","Compatible sous conditions","Aftermarket"],
  ["OEM-BR9ES","Bougie NGK BR9ES","Allumage","Applications multiples","Information insuffisante","Fabricant"],
  ["OEM-BR10EG","Bougie NGK BR10EG","Allumage","Compétition 2T","Information insuffisante","Fabricant"],
  ["AF-EXH-5070","Échappement détente 50/70","Échappement","50 à boîte","Compatible sous conditions","Aftermarket"],
  ["AF-IGN-DIGITAL","Allumage rotor interne digital","Allumage","Multi-moteurs","Adaptation nécessaire","Aftermarket"],
  ["OEM-YZ125-AIR","Filtre à air YZ125","Admission","Yamaha YZ125","Compatible sous conditions","OEM / à vérifier"],
  ["OEM-YZ125-CHAIN","Kit chaîne YZ125","Transmission","Yamaha YZ125","Compatible sous conditions","OEM / à vérifier"],
  ["OEM-EXC300-PISTON","Piston KTM 300 EXC","Haut moteur","KTM 300","Compatible sous conditions","OEM / à vérifier"],
  ["AF-2T-OIL-JASOFD","Huile 2T JASO FD","Lubrification","Applications multiples","Compatible sous conditions","Norme produit"],
  ["AF-GEAR-10W40","Huile boîte 10W-40 moto","Lubrification","Applications multiples","Information insuffisante","Norme produit"],
] as const;

const nav = [{id:"accueil" as View,label:"Accueil",icon:Home},{id:"assistant" as View,label:"Assistant IA",icon:Bot},{id:"configurateur" as View,label:"Configurateur",icon:Settings2},{id:"diagnostic" as View,label:"Diagnostic",icon:Stethoscope},{id:"base" as View,label:"Bibliothèque",icon:Database},{id:"pieces" as View,label:"Catalogue pièces",icon:PackageSearch},{id:"eclate" as View,label:"Vue éclatée",icon:Box},{id:"garage" as View,label:"Mon garage",icon:Wrench},{id:"pro" as View,label:"Espace professionnel",icon:Users}];
const proof = (kind:string) => <span className={`proof proof-${kind.toLowerCase().replaceAll(" ","-")}`}>{kind}</span>;

export default function HomePage() {
  const [view,setView] = useState<View>("accueil"); const [mobile,setMobile] = useState(false); const [query,setQuery] = useState("");
  const [selected,setSelected] = useState<Record<PartKey,number>>({cylinder:0,carb:0,exhaust:0,ignition:0,transmission:0}); const [activePart,setActivePart] = useState<PartKey>("cylinder");
  const [exploded,setExploded] = useState(false); const [saved,setSaved] = useState(false); const [diagStep,setDiagStep] = useState(0); const [garageApplied,setGarageApplied] = useState(false);
  const [assistantInput,setAssistantInput] = useState(""); const [assistantQuestion,setAssistantQuestion] = useState("Pourquoi mon moteur prend mal ses tours à chaud ?");
  const selectedParts = Object.entries(selected).map(([k,i])=>partOptions[k as PartKey][i]); const total = selectedParts.reduce((s,p)=>s+p.price,0); const performance = selectedParts.reduce((s,p)=>s+p.delta,0); const conditional = selectedParts.filter(p=>p.status==="Sous conditions").length;
  const results = useMemo(()=>{ const q=query.trim().toLowerCase(); return (q?vehicles.filter(v=>v.join(" ").toLowerCase().includes(q)):vehicles).slice(0,30); },[query]);

  useEffect(()=>{
    type Tool={name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:Record<string,unknown>)=>unknown};
    type ModelContext={registerTool:(tool:Tool,options?:{signal?:AbortSignal})=>void|Promise<void>};
    const context=(document as Document&{modelContext?:ModelContext}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    const register=(tool:Tool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>undefined)}catch{/* unsupported preview */}};
    register({name:"search_two_stroke_catalog",title:"Rechercher le catalogue 2T",description:"Recherche des machines dans le catalogue visible 2T Expert.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input)=>{const value=String(input.query??"");setQuery(value);setView("base");return {query:value,status:"displayed"}}});
    register({name:"open_two_stroke_workspace",title:"Ouvrir un espace 2T Expert",description:"Ouvre une fonction de 2T Expert.",inputSchema:{type:"object",properties:{view:{type:"string",enum:["accueil","assistant","configurateur","diagnostic","base","pieces","eclate","garage","pro"]}},required:["view"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input)=>{const next=String(input.view) as View;if(!nav.some(n=>n.id===next))throw new Error("Vue inconnue");setView(next);return {view:next,status:"opened"}}});
    register({name:"stage_configurator_part",title:"Préparer une modification du build",description:"Sélectionne une option de pièce dans le build DRAFT sans l'appliquer à la machine réelle.",inputSchema:{type:"object",properties:{category:{type:"string",enum:["cylinder","carb","exhaust","ignition","transmission"]},optionIndex:{type:"integer",minimum:0,maximum:2}},required:["category","optionIndex"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{const category=String(input.category) as PartKey;const optionIndex=Number(input.optionIndex);if(!partOptions[category]?.[optionIndex])throw new Error("Option indisponible");setSelected(current=>({...current,[category]:optionIndex}));setActivePart(category);setView("configurateur");return {category,optionIndex,part:partOptions[category][optionIndex].name,state:"DRAFT"}}});
    return()=>lifecycle.abort();
  },[]);

  const PageHead=({eyebrow,title,desc,actions}:{eyebrow:string;title:string;desc:string;actions?:React.ReactNode})=><div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{actions&&<div className="head-actions">{actions}</div>}</div>;
  const Metric=({label,value,delta,type,progress}:{label:string;value:string;delta:string;type:string;progress:number})=><div className="metric"><div><span>{label}</span>{proof(type)}</div><div className="metric-value"><b>{value}</b><small>{delta}</small></div><Progress value={Math.min(progress,100)}/></div>;

  const HomeView=()=> <div className="home-view"><section className="home-intro"><div><div className="eyebrow">PLATEFORME MONDIALE DES MOTEURS 2 TEMPS</div><h1>La mécanique 2T, claire et vérifiable.</h1><p>Identifiez une machine, consultez ses données, diagnostiquez un symptôme et préparez une configuration compatible depuis une seule base technique.</p><div className="home-search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")setView("base")}} placeholder="Marque, modèle, année, moteur, pièce, référence ou symptôme"/><Button onClick={()=>setView("base")}>Rechercher</Button></div><div className="home-trust"><ShieldCheck/><span>Chaque donnée publiée expose sa provenance, sa confiance et sa date de vérification.</span></div></div><Image src="/assets/two-stroke-supermoto.png" alt="Machine deux temps générique" width={1536} height={1024} priority/></section><section className="quick-grid">{[
    ["assistant","Diagnostic IA","Décrire un symptôme",Bot],["configurateur","Configurateur","Comparer CURRENT et DRAFT",Settings2],["base","Bibliothèque","Explorer les fiches techniques",BookOpen],["pieces","Pièces","Vérifier une compatibilité",PackageSearch],["garage","Garage","Suivre vos machines",Wrench],["pro","Professionnels","Gérer clients et interventions",Users]
  ].map(([id,title,desc,Icon])=><button key={String(id)} onClick={()=>setView(id as View)}><span><Icon/></span><b>{String(title)}</b><small>{String(desc)}</small><ChevronRight/></button>)}</section><section className="home-status"><div><span>COUVERTURE INITIALE</span><b>{vehicles.length} machines</b><small>{new Set(vehicles.map(v=>v[0])).size} marques · 50 à 500 cm³ · extension continue</small></div><div><span>PIÈCES INDEXÉES</span><b>{catalogParts.length} familles pilotes</b><small>Compatibilités conditionnelles explicitées</small></div><div><span>QUALITÉ</span><b>Truth Layer active</b><small>VERIFIED · CALCULATED · ESTIMATED · UNKNOWN</small></div><div><span>SERVICE</span><b>Mode dégradé disponible</b><small>Fiches et fonctions déterministes sans IA externe</small></div></section></div>;

  const Assistant=()=>{const q=assistantQuestion.toLowerCase();const hot=q.includes("chaud");const carb=q.includes("carbu")||q.includes("gicleur")||q.includes("tour");return <><PageHead eyebrow="IA TRANSVERSALE · RAG EXPLICABLE" title="Assistant mécanique 2T" desc="Une réponse contextualisée sur la machine, les données validées et les informations réellement disponibles."/><div className="assistant-layout"><section className="panel chat-panel"><div className="assistant-context"><span><Bot/></span><div><b>2T Expert AI</b><small>Mode sûr · base structurée prioritaire</small></div>{proof("CONFIANCE MODÉRÉE")}</div><div className="user-bubble">{assistantQuestion}</div><div className="ai-answer"><p><b>Je ne peux pas confirmer une cause unique sans identifier précisément la machine et effectuer des contrôles.</b> Pour ce symptôme, les pistes prioritaires sont :</p><ol><li><b>{hot?"Enrichissement ou défaut d'allumage à chaud":"Alimentation et carburation"}</b><span>{hot?"Comparer le comportement à froid/chaud et contrôler l'étincelle immédiatement après apparition.":"Contrôler alimentation, mise à l'air et réglage avant toute modification."}</span></li><li><b>{carb?"Réglage de carburation sous charge":"Étanchéité de l'admission"}</b><span>Documenter gicleurs, aiguille, filtre et couleur de bougie sans déduire un réglage d'un seul indice.</span></li><li><b>Compression et état mécanique</b><span>Mesurer avec le protocole constructeur applicable au moteur exact.</span></li></ol><div className="answer-evidence"><div><span>Périmètre</span><b>Machine non identifiée</b></div><div><span>Sources</span><b>Knowledge Engine local</b></div><div><span>Données manquantes</span><b>Modèle, année, configuration</b></div></div><div className="truth-note"><Info/><span>Ce résultat ordonne des contrôles ; il ne remplace ni une mesure ni une procédure constructeur.</span></div></div><form className="assistant-compose" onSubmit={e=>{e.preventDefault();if(assistantInput.trim()){setAssistantQuestion(assistantInput.trim());setAssistantInput("")}}}><Input value={assistantInput} onChange={e=>setAssistantInput(e.target.value)} placeholder="Décrivez le symptôme, le contexte et les modifications récentes…"/><Button type="submit"><Sparkles/>Analyser</Button></form></section><aside className="panel assistant-side"><div className="panel-title"><span>Contexte machine</span><CircleGauge/></div>{["Marque et modèle","Année et marché","Moteur / variante","Configuration actuelle"].map((x,i)=><button key={x} onClick={()=>setView("garage")}><span className={i===3?"pending":"ok"}>{i===3?"—":<Check/>}</span><span>{x}<small>{i===3?"À compléter":"Projet AM6 pilote"}</small></span><ChevronRight/></button>)}<div className="panel-title"><span>Capacités</span><ShieldCheck/></div><ul className="cap-list"><li>Recherche conversationnelle</li><li>Diagnostic guidé</li><li>Explication des compatibilités</li><li>Comparaison de builds</li><li>Refus si données insuffisantes</li></ul></aside></div></>};

  const Parts=()=>{const filtered=catalogParts.filter(p=>!query||p.join(" ").toLowerCase().includes(query.toLowerCase()));return <><PageHead eyebrow="BUY · DÉCISION TECHNIQUE INDÉPENDANTE" title="Catalogue pièces" desc="Références OEM, remplacement et préparation, reliées aux moteurs et aux conditions de montage."/><section className="panel knowledge"><div className="search-large"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Référence, désignation, moteur ou catégorie…"/><Badge>{filtered.length} pièce(s)</Badge></div><div className="result-table parts-table"><div className="table-head"><span>Référence</span><span>Pièce</span><span>Catégorie</span><span>Application</span><span>Verdict</span></div>{filtered.map(p=><button key={p[0]} onClick={()=>setView("configurateur")}><span><b>{p[0]}</b><small>{p[5]}</small></span><span>{p[1]}</span><span>{p[2]}</span><span>{p[3]}</span><span>{proof(p[4].includes("directement")?"VERIFIED":p[4].includes("insuffisante")?"UNKNOWN":"À VÉRIFIER")}<small>{p[4]}</small></span></button>)}</div><div className="data-disclaimer"><ShieldCheck/><span><b>Indépendance commerciale.</b> Aucun statut sponsorisé ne modifie le verdict technique. Les références pilotes à vérifier ne sont pas présentées comme certifiées.</span></div></section></>};

  const Professional=()=> <><PageHead eyebrow="ATELIER · ACCÈS PROTÉGÉ" title="Espace professionnel" desc="Dossiers clients, machines, interventions et exports, avec séparation stricte des comptes." actions={<Button asChild><a href="/signin-with-chatgpt?return_to=%2F">Se connecter</a></Button>}/><div className="pro-grid"><section className="panel pro-summary"><div className="panel-title"><span>Tableau de bord atelier</span><Users/></div><div className="pro-metrics"><div><b>12</b><span>Dossiers pilotes</span></div><div><b>18</b><span>Machines suivies</span></div><div><b>4</b><span>Interventions ouvertes</span></div></div><div className="pro-lock"><ShieldCheck/><div><b>Authentification requise</b><p>Les données de démonstration ci-dessus n'identifient aucun client réel. Connectez-vous pour créer un espace privé.</p></div></div></section><section className="panel pro-tools"><div className="panel-title"><span>Outils prévus</span><Wrench/></div>{["Clients et parc machines","Historique d'interventions","Diagnostic et notes atelier","Devis et listes de pièces","Exports de dossiers","Contributions techniques modérées"].map(x=><button key={x}><Check/>{x}<ChevronRight/></button>)}</section><aside className="panel coverage-admin"><div className="panel-title"><span>Couverture des données</span><Database/></div>{[["Machines indexées",vehicles.length,100],["Pièces pilotes",catalogParts.length,62],["Fiches vérifiées",8,18],["Données à valider",55,82]].map(([l,v,p])=><div className="coverage-row" key={String(l)}><span><b>{l}</b><small>{v} enregistrements</small></span><Progress value={Number(p)}/></div>)}</aside></div></>;

  const Configurator=()=>{ const labels:Record<PartKey,string>={cylinder:"Moteur / cylindre",carb:"Carburation",exhaust:"Échappement",ignition:"Allumage",transmission:"Transmission"}; return <><PageHead eyebrow="BUILD · Jumeau numérique" title="Configurateur professionnel" desc="Modifiez un build projeté sans altérer la configuration réellement installée." actions={<><Button variant="outline" onClick={()=>setSelected({cylinder:0,carb:0,exhaust:0,ignition:0,transmission:0})}><RotateCcw/>Réinitialiser</Button><Button onClick={()=>setSaved(true)}><Save/>{saved?"Build enregistré":"Enregistrer"}</Button></>}/><div className="config-grid">
    <section className="panel part-panel"><div className="panel-title"><div><span>Configuration DRAFT</span><small>Référence : machine générique AM6</small></div><Badge variant="outline">{conditional?`${conditional} condition(s)`:"Compatible"}</Badge></div><div className="part-tabs">{(Object.keys(partOptions) as PartKey[]).map(key=>{const p=partOptions[key][selected[key]];return <button key={key} className={activePart===key?"selected":""} onClick={()=>setActivePart(key)}><span className="part-icon">{key==="cylinder"?<Activity/>:key==="transmission"?<Gauge/>:<Wrench/>}</span><span><b>{labels[key]}</b><small>{p.name}</small></span><ChevronRight/></button>})}</div><div className="option-list"><div className="option-title">Remplacer {labels[activePart].toLowerCase()}</div>{partOptions[activePart].map((p,i)=><button key={p.name} className={selected[activePart]===i?"option active-option":"option"} onClick={()=>setSelected({...selected,[activePart]:i})}><span className="radio">{selected[activePart]===i&&<Check/>}</span><span><b>{p.name}</b><small>{p.note}</small></span><span className="option-price">{p.price?`${p.price} €`:"Installé"}<small>{p.status}</small></span></button>)}</div></section>
    <section className="panel visual-panel"><div className="view-toggle"><button className={!exploded?"on":""} onClick={()=>setExploded(false)}>Vue machine</button><button className={exploded?"on":""} onClick={()=>setExploded(true)}>Vue éclatée</button></div><div className="machine-stage"><Image src={exploded?"/assets/two-stroke-exploded.png":"/assets/two-stroke-supermoto.png"} alt={exploded?"Vue éclatée originale d'un moteur deux temps générique":"Rendu 3D original d'une supermotard deux temps générique"} fill priority sizes="(max-width: 900px) 100vw, 50vw"/><button className="hotspot h1" onClick={()=>setActivePart("cylinder")}>1</button><button className="hotspot h2" onClick={()=>setActivePart("exhaust")}>2</button><div className="asset-label"><Box/> Rendu original générique · 360° à connecter</div></div><div className="machine-meta"><span><b>État affiché</b>DRAFT</span><span><b>Base moteur</b>AM6</span><span><b>Marché</b>Europe</span><span><b>Complétude</b>72 %</span></div></section>
    <section className="panel realtime"><div className="panel-title"><div><span>Performances temps réel</span><small>Comparaison CURRENT → DRAFT</small></div><GitCompareArrows/></div><Metric label="Vitesse théorique" value={`${82+performance*2} km/h`} delta={performance?`+${performance*2} km/h`:"Référence"} type="CALCULÉ" progress={62+performance*2}/><Metric label="Puissance exploitable" value={`${8+performance}–${10+performance} ch`} delta={performance?"Fourchette élargie":"Estimation de démo"} type="ESTIMÉ" progress={45+performance*3}/><Metric label="Endurance" value={performance>7?"Moyenne":"Bonne"} delta={performance>7?"Contrôles renforcés":"Configuration modérée"} type="QUALITATIF" progress={performance>7?52:78}/><div className="truth-note"><Info/><span><b>Pourquoi ces résultats ?</b> Valeurs de démonstration uniquement : aucune publication réelle sans source ou modèle calibré.</span></div><div className="budget"><span>Budget des modifications</span><b>{total.toLocaleString("fr-FR")} €</b></div><Button className="wide" variant={conditional?"outline":"default"} onClick={()=>setGarageApplied(true)}>{conditional?"Voir les conditions":"Appliquer à ma machine"}</Button></section>
  </div></> };

  const Diagnostic=()=>{const steps=[{q:"Dans quelle situation le problème apparaît-il ?",a:["Démarrage à froid","Démarrage à chaud","En accélération","À régime stabilisé"]},{q:"Quel symptôme décrit le mieux la panne ?",a:["Difficulté de démarrage","Perte de puissance","Ratés / pétarades","Surchauffe apparente"]},{q:"Une modification récente a-t-elle été effectuée ?",a:["Carburation","Admission / échappement","Allumage","Aucune modification connue"]}]; const done=diagStep>=steps.length; return <><PageHead eyebrow="DIAGNOSE · Assisté et explicable" title="Diagnostic guidé" desc="Le diagnostic utilise le véhicule, sa configuration actuelle et les contrôles réalisés."/><div className="diagnostic-grid"><section className="panel diagnostic-machine"><div className="panel-title"><span>Machine analysée</span>{proof("VERIFIED")}</div><Image src="/assets/two-stroke-supermoto.png" alt="Machine générique utilisée pour le diagnostic" width={1536} height={1024}/><div className="machine-summary"><b>Projet AM6 · Configuration CURRENT</b><span>Historique et composants reliés au même jumeau numérique</span></div><div className="diag-zones"><button>Admission</button><button>Allumage</button><button>Carburation</button><button>Transmission</button></div></section><section className="panel diag-flow">{!done?<><div className="stepper">Étape {diagStep+1} sur {steps.length}<Progress value={(diagStep+1)/steps.length*100}/></div><h2>{steps[diagStep].q}</h2><div className="answer-grid">{steps[diagStep].a.map(a=><button key={a} onClick={()=>setDiagStep(diagStep+1)}><span>{a}</span><ChevronRight/></button>)}</div><button className="unknown" onClick={()=>setDiagStep(diagStep+1)}>Je ne sais pas</button></>:<div className="diagnosis-result"><div className="result-icon"><Sparkles/></div><div className="eyebrow">HYPOTHÈSES À CONTRÔLER</div><h2>Le parcours est prêt pour les contrôles terrain</h2><p>Aucune conclusion mécanique certaine ne peut être affirmée sans mesures. Le système propose une séquence sûre et traçable.</p><ol><li><b>Contrôle visuel et étanchéité</b><span>Vérifier durites, colliers, boîte à air et admission.</span></li><li><b>Lecture de la bougie</b><span>Documenter l'état, la référence et l'écartement.</span></li><li><b>Mesure de compression</b><span>Comparer à une valeur constructeur sourcée.</span></li></ol><Button onClick={()=>setDiagStep(0)}><RotateCcw/>Recommencer</Button></div>}</section><aside className="panel diag-context"><div className="panel-title"><span>Contexte utilisé</span><ShieldCheck/></div>{["Configuration CURRENT","Historique des interventions","Symptômes déclarés","Sources techniques validées"].map((x,i)=><div className="context-row" key={x}><span className={i<2?"ok":"pending"}>{i<2?<Check/>:"—"}</span><span>{x}<small>{i<2?"Disponible":"À enrichir"}</small></span></div>)}<div className="truth-note"><Info/><span>Une hypothèse n'est jamais présentée comme une certitude.</span></div></aside></div></>};

  const Knowledge=()=> <><PageHead eyebrow="KNOW · Knowledge Engine" title="Base technique universelle" desc={`${vehicles.length} références de couverture initiale, regroupées par moteur et catégorie.`}/><section className="panel knowledge"><div className="search-large"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex. AM6, YZ125, enduro 300, RD350…"/><Badge>{results.length} résultat(s)</Badge></div><div className="coverage"><span><b>{new Set(vehicles.map(v=>v[0])).size}</b> marques</span><span><b>{vehicles.length}</b> modèles</span><span><b>9</b> segments</span><span><b>7</b> familles de données</span></div><div className="result-table"><div className="table-head"><span>Machine</span><span>Segment</span><span>Moteur / famille</span><span>Années indicatives</span><span>Statut</span></div>{results.map((v,i)=><button key={`${v[0]}-${v[1]}-${i}`}><span><b>{v[0]}</b> {v[1]}</span><span>{v[2]}</span><span>{v[3]}</span><span>{v[4]}</span><span>{proof(i%5===0?"À VÉRIFIER":"INDEXÉ")}</span></button>)}</div><div className="data-disclaimer"><Info/><span><b>Couverture, pas certification.</b> Les années, variantes et valeurs techniques passent par le pipeline de validation avant publication comme données vérifiées.</span></div></section></>;
  const Exploded=()=> <><PageHead eyebrow="KNOW · Asset Registry" title="Vue éclatée interactive" desc="Une même référence de composant alimente l'éclaté, le configurateur, le diagnostic et les compatibilités."/><div className="exploded-grid"><section className="panel exploded-stage"><Image src="/assets/two-stroke-exploded.png" alt="Vue éclatée originale et générique d'un moteur deux temps" fill sizes="(max-width: 900px) 100vw, 70vw"/><button className="exploded-point ep1">01</button><button className="exploded-point ep2">02</button><button className="exploded-point ep3">03</button><div className="zoom-tools"><Button size="icon" variant="outline">+</Button><Button size="icon" variant="outline">−</Button></div></section><aside className="panel component-card"><div className="component-number">01</div><div className="eyebrow">SOUS-ENSEMBLE</div><h2>Cylindre et haut moteur</h2><p>Représentation originale générique. Les hotspots sont prêts à recevoir les identifiants canoniques des pièces licenciées ou sourcées.</p><dl><div><dt>Type</dt><dd>Mono-cylindre 2T</dd></div><div><dt>Référence</dt><dd>GEN-2T-TOP-001</dd></div><div><dt>Preuve</dt><dd>{proof("ILLUSTRATION")}</dd></div><div><dt>Compatibilité</dt><dd>{proof("UNKNOWN")}</dd></div></dl><Button onClick={()=>{setActivePart("cylinder");setView("configurateur")}}>Ouvrir dans le configurateur<ChevronRight/></Button></aside></div></>;
  const Garage=()=> <><PageHead eyebrow="Jumeau numérique versionné" title="Mon garage" desc="Configuration d'origine, état installé et projets restent séparés et traçables." actions={<Button><Zap/>Ajouter une machine</Button>}/><div className="garage-grid"><section className="panel garage-vehicle"><Image src="/assets/two-stroke-supermoto.png" alt="Machine générique du garage" width={1536} height={1024}/><div><Badge>Machine principale</Badge><h2>Projet Supermotard AM6</h2><p>Identifiant 2T : 2TE-DEMO-AM6-001</p></div><div className="garage-actions"><Button onClick={()=>setView("configurateur")}>Configurer</Button><Button variant="outline" onClick={()=>setView("diagnostic")}>Diagnostiquer</Button></div></section><section className="panel timeline"><div className="panel-title"><span>Historique de configuration</span><BookOpen/></div>{[{state:"CURRENT",title:"Configuration installée",date:"Aujourd'hui",text:"Base 49,7 cm³ · 13 × 53 · composants d'origine"},{state:"DRAFT",title:"Build sport sauvegardé",date:saved?"À l'instant":"Non enregistré",text:saved?`${total} € · ${conditional} condition(s) à résoudre`:"Créez un projet depuis le configurateur"},{state:"ORIGINAL",title:"Configuration d'origine",date:"Référence",text:"Données constructeur à sourcer"}].map((x,i)=><div className="timeline-row" key={x.state}><span className={`timeline-dot t${i}`}/><div><span>{x.state}</span><b>{x.title}</b><p>{x.text}</p></div><small>{x.date}</small></div>)}</section><aside className="panel maintenance"><div className="panel-title"><span>État technique</span><CircleGauge/></div><div className="health"><b>72 %</b><span>fiche complétée</span><Progress value={72}/></div><h3>À renseigner pour fiabiliser les résultats</h3>{["Kilométrage actuel","Référence de bougie","Réglage de carburation","Masse pilote + équipement"].map(x=><button key={x}><PackageSearch/>{x}<ChevronRight/></button>)}{garageApplied&&<div className="saved-note"><Check/> Build marqué comme projet DRAFT</div>}</aside></div></>;

  return <div className="app-shell"><header className="topbar"><button className="mobile-menu" aria-label="Ouvrir le menu" onClick={()=>setMobile(!mobile)}><Menu/></button><button className="brand" onClick={()=>setView("accueil")}><span>2T</span> EXPERT<small>KNOW · DIAGNOSE · BUILD · BUY</small></button><div className="global-search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} onFocus={()=>setView("base")} placeholder="Rechercher une machine, un moteur, une pièce…" aria-label="Recherche universelle"/></div><Button variant="outline" className="account" asChild><a href="/signin-with-chatgpt?return_to=%2F"><UserRound/> Se connecter</a></Button></header><aside className={`sidebar ${mobile?"sidebar-open":""}`}><div className="side-label">PLATEFORME</div>{nav.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>{setView(item.id);setMobile(false)}}><item.icon/><span>{item.label}</span></button>)}<div className="side-label">QUALITÉ DES DONNÉES</div><div className="quality-card"><ShieldCheck/><div><b>Truth Layer active</b><span>Mesure, calcul et estimation restent distincts.</span></div></div><div className="sidebar-foot"><span>Master V10</span><span>FR · métrique</span></div></aside><main className="workspace">{view==="accueil"&&<HomeView/>}{view==="assistant"&&<Assistant/>}{view==="configurateur"&&<Configurator/>}{view==="diagnostic"&&<Diagnostic/>}{view==="base"&&<Knowledge/>}{view==="pieces"&&<Parts/>}{view==="eclate"&&<Exploded/>}{view==="garage"&&<Garage/>}{view==="pro"&&<Professional/>}</main></div>;
}
